<?php
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Database\Database;


function glossary_module_theme($existing, $type, $theme, $path) {
  return [
    'page--glossary_module' => [
      'variables' => [ 
        'content' => [],
      ],
      'template' => 'page--glossary_module',
    ],
  ];
}

function glossary_module_page_attachments_alter(array &$attachments)
{
  $route_uri = \Drupal::request()->getRequestUri();

  if(str_starts_with($route_uri, '/glossary_module/')) {
    $attachments['#attached']['library'][] = 'glossary_module/glossary_style';
  }
}

?>